# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.6
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: ynd

    working_directory: ~/repo

    environment:
      DB_HOST: "localhost"
      DB_USERNAME: "postgres"
      DB_PASSWORD: ""
      DB_NAME: "ynd"

    steps:
      - checkout
      - run: mix local.rebar --force && mix local.hex --force && mix archive.install https://github.com/phoenixframework/archives/raw/master/phx_new.ez --force

      # specify any bash command here prefixed with `run: `
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix test